micrograph_path: Frames/GDP_curved_mgraph.mrc
template_volume_path: maps/6dpu_atoms_6dpu_lattice_2rings_flatB_0.9194_bscale0.5.mrc
computational_config:
  gpu_ids:
  - 0
  - 1
  - 2
  - 3
  num_cpus: 8
defocus_search_config:
  enabled: true
  defocus_max: 600.0
  defocus_min: -600.0
  defocus_step: 200.0
match_template_result:
  allow_file_overwrite: true
  correlation_average_path: results_gdp_curved/output_correlation_average_gdp_curved_14pf_expanded.mrc
  correlation_variance_path: results_gdp_curved/output_correlation_variance_gdp_curved_14pf_expanded.mrc
  mip_path: results_gdp_curved/output_mip_gdp_curved_14pf_expanded.mrc
  orientation_phi_path: results_gdp_curved/output_orientation_phi_gdp_curved_14pf_expanded.mrc
  orientation_psi_path: results_gdp_curved/output_orientation_psi_gdp_curved_14pf_expanded.mrc
  orientation_theta_path: results_gdp_curved/output_orientation_theta_gdp_curved_14pf_expanded.mrc
  relative_defocus_path: results_gdp_curved/output_relative_defocus_gdp_curved_14pf_expanded.mrc
  scaled_mip_path: results_gdp_curved/output_scaled_mip_gdp_curved_14pf_expanded.mrc
optics_group:
  label: GDP_curved_mgraph
  amplitude_contrast_ratio: 0.07
  ctf_B_factor: 60.0
  astigmatism_angle: -8.400406971516361
  defocus_u: 2104.2926609516144
  defocus_v: 1873.9201128482819
  phase_shift: 0.0
  pixel_size: 0.9194
  spherical_aberration: 2.7
  voltage: 300.0
orientation_search_config:
  base_grid_method: uniform
  psi_step: 2.5      # in degrees
  theta_step: 3.5  # in degrees
preprocessing_filters:
  bandpass_filter:
    enabled: false
    falloff: 0.05
    high_freq_cutoff: 0.5
    low_freq_cutoff: 0.0
  whitening_filter:
    enabled: true
    do_power_spectrum: true
    max_freq: 1.0
    num_freq_bins: null
